<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>Nuklear.Net</RootNamespace>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>Nuklear.Net</PackageId>
    <Version>1.0.0</Version>
    <Authors>SimonSeider</Authors>
    <Description>.NET bindings for the Nuklear immediate-mode GUI library.</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <PackageTags>nuklear;imgui;immediate-mode;gui;ui;bindings;native;interop;pinvoke</PackageTags>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>

  <ItemGroup>
    <None Include="../README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Nuklear.Net.Native\Nuklear.Net.Native.csproj" />
  </ItemGroup>
  
  <Import Project="..\Nuklear.Net.Native\buildTransitive\$(TargetFramework)\Nuklear.Net.Native.targets"
          Condition="Exists('..\Nuklear.Net.Native\buildTransitive\$(TargetFramework)\Nuklear.Net.Native.targets')" />

</Project>
